import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  imageBackground: {
    flex: 1,
  },
  background: {
    flex: 1,
    backgroundColor: 'rgba(28, 31, 29, 0.5)',
  },
  titleRegister: {
    fontFamily: 'Roboto-Black',
    lineHeight: 42,
    color: '#fff',
    fontSize: 36,
    marginTop: 100,
    marginBottom: 70,
    paddingLeft: 30,
    paddingRight: 60,
  },
  errorText: {
    position: 'absolute',
    top: 230,
    left: 30,
    height: 25,
    color: 'red',
    backgroundColor: 'rgba(24, 26, 24, 0.7)',
    fontSize: 16,
    fontWeight: '700',
    borderRadius: 10,
  },
  input: {
    backgroundColor: 'rgba(217, 217, 217, 0.5)',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginHorizontal: 25,
    marginTop: 20,
    fontWeight: '900',
    height: '7%',
    color: '#fff',
  },
  middleText: {
    fontFamily: 'Nunito-Regular',
    textDecorationLine: 'underline',
    alignSelf: 'flex-start',
    color: '#fff',
    paddingHorizontal: 30,
    marginTop: 8,
  },
  buttonRegister: {
    height: '7%',
    marginHorizontal: 25,
    marginTop: 30,
    backgroundColor: '#FFCD61',
    borderRadius: 10,
    justifyContent: 'center',
  },
  textButton: {
    color: '#393939',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 25,
    textAlign: 'center',
  },
  buttonGoogle: {
    height: 51,
    marginHorizontal: 25,
    marginTop: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    justifyContent: 'center',
  },
  subtitleText: {
    fontFamily: 'Nunito-Regular',
    textAlign: 'center',
    fontSize: 14,
    color: '#fff',
    marginVertical: 40,
  },
  lineSubtitle: {
    textDecorationLine: 'underline',
    fontWeight: '700',
  },
  buttonWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  buttonRight: {
    width: 60,
    height: 35,
    marginTop: 30,
    borderRadius: 10,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFCD61',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.36,
    shadowRadius: 6.68,
    elevation: 11,
  },
  textButtonRight: {
    fontSize: 15,
    fontWeight: '600',
  },
  textButtonLeft: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFCD61',
  },
  buttonLeft: {
    width: 60,
    height: 35,
    marginTop: 30,
    borderRadius: 10,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#393939',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.36,
    shadowRadius: 6.68,
    elevation: 11,
  },
});
