import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  imageBackground: {
    flex: 1,
  },
  background: {
    flex: 1,
    backgroundColor: 'rgba(28, 31, 29, 0.5)',
  },
  titleLogin: {
    fontFamily: 'Roboto-Black',
    lineHeight: 42,
    color: '#fff',
    fontSize: 36,
    marginVertical: 105,
    paddingLeft: 30,
    paddingRight: 60,
  },
  errorText: {
    position: 'absolute',
    top: 280,
    left: 30,
    height: 25,
    color: 'red',
    backgroundColor: 'rgba(24, 26, 24, 0.7)',
    fontSize: 16,
    fontWeight: '700',
    borderRadius: 10,
  },
  input: {
    backgroundColor: 'rgba(217, 217, 217, 0.5)',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginHorizontal: 25,
    marginTop: 20,
    fontWeight: '900',
    height: '7%',
    color: '#fff',
  },
  middleText: {
    fontFamily: 'Nunito-Regular',
    textDecorationLine: 'underline',
    alignSelf: 'flex-start',
    color: '#fff',
    paddingHorizontal: 30,
    marginTop: 8,
  },
  buttonLogin: {
    height: '7%',
    marginHorizontal: 25,
    marginTop: 30,
    backgroundColor: '#FFCD61',
    borderRadius: 10,
    justifyContent: 'center',
  },
  textButton: {
    color: '#393939',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 25,
    textAlign: 'center',
  },
  buttonGoogle: {
    height: '7%',
    marginHorizontal: 25,
    marginTop: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    justifyContent: 'center',
  },
  subtitleText: {
    fontFamily: 'Nunito-Regular',
    textAlign: 'center',
    fontSize: 14,
    color: '#fff',
    marginVertical: 40,
  },
  lineSubtitle: {
    textDecorationLine: 'underline',
    fontWeight: '700',
  },
});
