import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  loading: {
    height: '100%',
    justifyContent: 'center',
  },
  container: {
    backgroundColor: '#fff',
  },
  scrollContainer: {
    backgroundColor: '#fff',
  },
  iconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    fontSize: 20,
    marginVertical: 15,
    marginHorizontal: 15,
  },
  icon: {
    fontSize: 30,
  },
  textIcon: {
    fontFamily: 'Nunito-Regular',
    fontSize: 25,
    fontWeight: 'bold',
    color: '#393939',
    marginLeft: 10,
  },
  imageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 15,
  },
  imageProfile: {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    marginBottom: 5,
  },
  gender: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  genderOptions: {
    flexDirection: 'row',
    marginHorizontal: 20,
    alignItems: 'center',
  },
  text: {
    marginHorizontal: 30,
    marginTop: 20,
    marginBottom: 15,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: 'gray',
    paddingHorizontal: 15,
    marginHorizontal: 25,
    color: '#393939',
    fontWeight: '900',
    width: 338,
    height: 52,
  },
  date: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: 'gray',
    paddingHorizontal: 15,
    paddingVertical: 15,
    marginHorizontal: 25,
    width: 338,
    height: 52,
  },
  textDate: {
    color: '#393939',
    fontWeight: '900',
  },
  button: {
    width: 338,
    height: 57,
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 30,
    backgroundColor: '#FFCD61',
    borderRadius: 10,
    // justifyContent: 'center',
  },
  textButton: {
    color: '#393939',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 25,
    textAlign: 'center',
  },
  editImage: {
    position: 'absolute',
    top: 150,
    left: 215,
    width: 35,
    height: 35,
    borderRadius: 35,
    backgroundColor: '#FFCD61',
  },
  textEditImage: {
    fontSize: 30,
    fontWeight: '600',
    lineHeight: 35,
    color: '#393939',
    textAlign: 'center',
  },
});
